name: Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup
      run: make setup

    - name: make
      run: make release

    - name: upload
      uses: actions/upload-artifact@v4.3.3
      with:
        name: gosh.zip
        path: release
        if-no-files-found: error
